package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"
	"strings"

	"github.com/robinsr/taggedfilebrowser/server/db/queries"
	"github.com/robinsr/taggedfilebrowser/server/graph"
	"github.com/robinsr/taggedfilebrowser/server/graph/model"
)

// Tags is the resolver for the tags field.
func (r *fileResolver) Tags(ctx context.Context, obj *model.File) ([]*model.Tag, error) {
	rows, err := queries.ListTagsForFile(ctx, r.db, obj.ID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Tag, len(rows))
	for i, t := range rows {
		out[i] = tagRowToModel(t)
	}
	return out, nil
}

// TagCount is the resolver for the tagCount field.
func (r *fileResolver) TagCount(ctx context.Context, obj *model.File) (int, error) {
	return queries.GetFileTagCount(ctx, r.db, obj.ID)
}

// Bookmarked is the resolver for the bookmarked field.
func (r *fileResolver) Bookmarked(ctx context.Context, obj *model.File) (bool, error) {
	return queries.IsFileBookmarked(ctx, r.db, obj.ID)
}

// Queues is the resolver for the queues field.
func (r *fileResolver) Queues(ctx context.Context, obj *model.File) ([]*model.Queue, error) {
	queueRows, err := queries.ListQueuesForFile(ctx, r.db, obj.ID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Queue, len(queueRows))
	for i, q := range queueRows {
		items, err := queries.ListQueueItems(ctx, r.db, q.ID)
		if err != nil {
			return nil, err
		}
		out[i] = queueRowToModel(q, items)
	}
	return out, nil
}

// History is the resolver for the history field.
func (r *fileResolver) History(ctx context.Context, obj *model.File) ([]*model.FileHistoryEntry, error) {
	panic(fmt.Errorf("not implemented: History - history"))
}

// File is the resolver for the file field.
func (r *queryResolver) File(ctx context.Context, id string) (*model.File, error) {
	row, err := queries.GetFile(ctx, r.db, id)
	if err != nil || row == nil {
		return nil, err
	}
	return fileRowToModel(row), nil
}

// Files is the resolver for the files field.
func (r *queryResolver) Files(ctx context.Context, filter *model.FileFilterInput, first *int, after *string) (*model.FileConnection, error) {
	f := parseFileFilter(filter)
	n := 20
	if first != nil {
		n = *first
	}
	cursor := ""
	if after != nil {
		cursor = *after
	}
	list, err := queries.ListFiles(ctx, r.db, f, n, cursor)
	if err != nil {
		return nil, err
	}
	return fileListToConnection(list), nil
}

// Tag is the resolver for the tag field.
func (r *queryResolver) Tag(ctx context.Context, id string) (*model.Tag, error) {
	row, err := queries.GetTag(ctx, r.db, id)
	if err != nil || row == nil {
		return nil, err
	}
	return tagRowToModel(row), nil
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context, domain *model.TagDomain, typeArg *model.TagType) ([]*model.Tag, error) {
	var domainStr *string
	var tagTypeStr *string
	if domain != nil {
		s := strings.ToLower(string(*domain))
		domainStr = &s
	}
	if typeArg != nil {
		s := dbTagTypeRawValue(*typeArg)
		tagTypeStr = &s
	}
	rows, err := queries.ListTags(ctx, r.db, domainStr, tagTypeStr)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Tag, len(rows))
	for i, t := range rows {
		out[i] = tagRowToModel(t)
	}
	return out, nil
}

// SavedQuery is the resolver for the savedQuery field.
func (r *queryResolver) SavedQuery(ctx context.Context, id string) (*model.SavedQuery, error) {
	panic(fmt.Errorf("not implemented: SavedQuery - savedQuery"))
}

// SavedQueries is the resolver for the savedQueries field.
func (r *queryResolver) SavedQueries(ctx context.Context) ([]*model.SavedQuery, error) {
	panic(fmt.Errorf("not implemented: SavedQueries - savedQueries"))
}

// SavedQueryResults is the resolver for the savedQueryResults field.
func (r *queryResolver) SavedQueryResults(ctx context.Context, id string, first *int, after *string) (*model.FileConnection, error) {
	panic(fmt.Errorf("not implemented: SavedQueryResults - savedQueryResults"))
}

// Bookmarks is the resolver for the bookmarks field.
func (r *queryResolver) Bookmarks(ctx context.Context) ([]*model.Bookmark, error) {
	rows, err := queries.ListBookmarks(ctx, r.db)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Bookmark, len(rows))
	for i, b := range rows {
		out[i] = bookmarkRowToModel(b)
	}
	return out, nil
}

// Queue is the resolver for the queue field.
func (r *queryResolver) Queue(ctx context.Context, id string) (*model.Queue, error) {
	q, err := queries.GetQueue(ctx, r.db, id)
	if err != nil || q == nil {
		return nil, err
	}
	items, err := queries.ListQueueItems(ctx, r.db, id)
	if err != nil {
		return nil, err
	}
	return queueRowToModel(q, items), nil
}

// Queues is the resolver for the queues field.
func (r *queryResolver) Queues(ctx context.Context) ([]*model.Queue, error) {
	queueRows, err := queries.ListQueues(ctx, r.db)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Queue, len(queueRows))
	for i, q := range queueRows {
		items, err := queries.ListQueueItems(ctx, r.db, q.ID)
		if err != nil {
			return nil, err
		}
		out[i] = queueRowToModel(q, items)
	}
	return out, nil
}

// Domain is the resolver for the domain field.
func (r *tagResolver) Domain(ctx context.Context, obj *model.Tag) (model.TagDomain, error) {
	return obj.Domain, nil
}

// Aliases is the resolver for the aliases field.
func (r *tagResolver) Aliases(ctx context.Context, obj *model.Tag) ([]*model.Tag, error) {
	rows, err := queries.ListAliasesForTag(ctx, r.db, obj.ID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Tag, len(rows))
	for i, t := range rows {
		out[i] = tagRowToModel(t)
	}
	return out, nil
}

// Parent is the resolver for the parent field.
func (r *tagResolver) Parent(ctx context.Context, obj *model.Tag) (*model.Tag, error) {
	// relatedId is not stored in model.Tag; re-fetch the row to get it.
	row, err := queries.GetTag(ctx, r.db, obj.ID)
	if err != nil || row == nil || row.RelatedID == nil {
		return nil, err
	}
	parent, err := queries.GetTag(ctx, r.db, *row.RelatedID)
	if err != nil || parent == nil {
		return nil, err
	}
	return tagRowToModel(parent), nil
}

// FileCount is the resolver for the fileCount field.
func (r *tagResolver) FileCount(ctx context.Context, obj *model.Tag) (int, error) {
	return queries.CountFilesForTag(ctx, r.db, obj.ID)
}

// Files is the resolver for the files field.
func (r *tagResolver) Files(ctx context.Context, obj *model.Tag, first *int, after *string) (*model.FileConnection, error) {
	n := 20
	if first != nil {
		n = *first
	}
	cursor := ""
	if after != nil {
		cursor = *after
	}
	list, err := queries.ListFilesForTag(ctx, r.db, obj.ID, n, cursor)
	if err != nil {
		return nil, err
	}
	return fileListToConnection(list), nil
}

// File returns graph.FileResolver implementation.
func (r *Resolver) File() graph.FileResolver { return &fileResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

// Tag returns graph.TagResolver implementation.
func (r *Resolver) Tag() graph.TagResolver { return &tagResolver{r} }

type (
	fileResolver  struct{ *Resolver }
	queryResolver struct{ *Resolver }
	tagResolver   struct{ *Resolver }
)
