package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	"github.com/robinsr/taggedfilebrowser/server/graph"
)

// Placeholder is the resolver for the _placeholder field.
func (r *queryResolver) Placeholder(ctx context.Context) (*bool, error) {
	panic(fmt.Errorf("not implemented: Placeholder - _placeholder"))
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
