// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Bookmark struct {
	ID        string `json:"id"`
	File      *File  `json:"file"`
	CreatedAt string `json:"createdAt"`
}

type File struct {
	ID         string              `json:"id"`
	Name       string              `json:"name"`
	Location   string              `json:"location"`
	Type       string              `json:"type"`
	Size       int                 `json:"size"`
	Created    string              `json:"created"`
	Modified   string              `json:"modified"`
	Comment    string              `json:"comment"`
	Volume     string              `json:"volume"`
	Visibility FileVisibility      `json:"visibility"`
	Tags       []*Tag              `json:"tags"`
	TagCount   int                 `json:"tagCount"`
	Bookmarked bool                `json:"bookmarked"`
	Queues     []*Queue            `json:"queues"`
	History    []*FileHistoryEntry `json:"history"`
}

type FileConnection struct {
	Edges      []*FileEdge `json:"edges"`
	Nodes      []*File     `json:"nodes"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

type FileEdge struct {
	Cursor string `json:"cursor"`
	Node   *File  `json:"node"`
}

type FileFilter struct {
	Root           *string            `json:"root,omitempty"`
	Traversal      *TraversalMode     `json:"traversal,omitempty"`
	SortBy         *SortOrder         `json:"sortBy,omitempty"`
	Visibility     *VisibilityFilter  `json:"visibility,omitempty"`
	Types          []ContentTypeGroup `json:"types,omitempty"`
	NameMatching   *NameFilter        `json:"nameMatching,omitempty"`
	ExcludeContent *NameFilter        `json:"excludeContent,omitempty"`
	TagsMatching   *TagsFilter        `json:"tagsMatching,omitempty"`
}

type FileFilterInput struct {
	Root           *string            `json:"root,omitempty"`
	Traversal      *TraversalMode     `json:"traversal,omitempty"`
	SortBy         *SortOrder         `json:"sortBy,omitempty"`
	Visibility     *VisibilityFilter  `json:"visibility,omitempty"`
	Types          []ContentTypeGroup `json:"types,omitempty"`
	NameMatching   *NameMatchingInput `json:"nameMatching,omitempty"`
	ExcludeContent *NameMatchingInput `json:"excludeContent,omitempty"`
	TagsMatching   *TagsMatchingInput `json:"tagsMatching,omitempty"`
}

type FileHistoryEntry struct {
	ID        string        `json:"id"`
	Timestamp string        `json:"timestamp"`
	Column    HistoryColumn `json:"column"`
	OldValue  string        `json:"oldValue"`
	NewValue  string        `json:"newValue"`
	FsStatus  FsStatus      `json:"fsStatus"`
	IndexType *string       `json:"indexType,omitempty"`
}

type NameFilter struct {
	Operator FilterOperator `json:"operator"`
	Values   []string       `json:"values"`
}

type NameMatchingInput struct {
	Operator FilterOperator `json:"operator"`
	Values   []string       `json:"values"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type Queue struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	Created   string       `json:"created"`
	ItemCount int          `json:"itemCount"`
	Items     []*QueueItem `json:"items"`
}

type QueueItem struct {
	ID        string `json:"id"`
	File      *File  `json:"file"`
	AddedAt   string `json:"addedAt"`
	Completed bool   `json:"completed"`
}

type SavedQuery struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Filter    *FileFilter `json:"filter"`
	CreatedAt string      `json:"createdAt"`
	UpdatedAt string      `json:"updatedAt"`
}

type Tag struct {
	ID        string          `json:"id"`
	TagValue  string          `json:"tagValue"`
	TagType   TagType         `json:"tagType"`
	Domain    TagDomain       `json:"domain"`
	EntryType TagEntryType    `json:"entryType"`
	Aliases   []*Tag          `json:"aliases"`
	Parent    *Tag            `json:"parent,omitempty"`
	FileCount int             `json:"fileCount"`
	Files     *FileConnection `json:"files"`
}

type TagCriterion struct {
	Effect   TagFilterEffect `json:"effect"`
	TagType  TagType         `json:"tagType"`
	TagValue string          `json:"tagValue"`
}

type TagCriterionInput struct {
	Effect   TagFilterEffect `json:"effect"`
	TagType  TagType         `json:"tagType"`
	TagValue string          `json:"tagValue"`
}

type TagsFilter struct {
	Enabled  bool            `json:"enabled"`
	Operator FilterOperator  `json:"operator"`
	Criteria []*TagCriterion `json:"criteria"`
}

type TagsMatchingInput struct {
	Enabled  bool                 `json:"enabled"`
	Operator FilterOperator       `json:"operator"`
	Criteria []*TagCriterionInput `json:"criteria"`
}

type ContentTypeGroup string

const (
	ContentTypeGroupFolders  ContentTypeGroup = "FOLDERS"
	ContentTypeGroupImages   ContentTypeGroup = "IMAGES"
	ContentTypeGroupVideo    ContentTypeGroup = "VIDEO"
	ContentTypeGroupDatabase ContentTypeGroup = "DATABASE"
	ContentTypeGroupUser     ContentTypeGroup = "USER"
	ContentTypeGroupNonUser  ContentTypeGroup = "NON_USER"
	ContentTypeGroupContent  ContentTypeGroup = "CONTENT"
	ContentTypeGroupAll      ContentTypeGroup = "ALL"
	ContentTypeGroupEmpty    ContentTypeGroup = "EMPTY"
)

var AllContentTypeGroup = []ContentTypeGroup{
	ContentTypeGroupFolders,
	ContentTypeGroupImages,
	ContentTypeGroupVideo,
	ContentTypeGroupDatabase,
	ContentTypeGroupUser,
	ContentTypeGroupNonUser,
	ContentTypeGroupContent,
	ContentTypeGroupAll,
	ContentTypeGroupEmpty,
}

func (e ContentTypeGroup) IsValid() bool {
	switch e {
	case ContentTypeGroupFolders, ContentTypeGroupImages, ContentTypeGroupVideo, ContentTypeGroupDatabase, ContentTypeGroupUser, ContentTypeGroupNonUser, ContentTypeGroupContent, ContentTypeGroupAll, ContentTypeGroupEmpty:
		return true
	}
	return false
}

func (e ContentTypeGroup) String() string {
	return string(e)
}

func (e *ContentTypeGroup) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ContentTypeGroup(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ContentTypeGroup", str)
	}
	return nil
}

func (e ContentTypeGroup) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ContentTypeGroup) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ContentTypeGroup) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FileVisibility string

const (
	FileVisibilityNormal FileVisibility = "NORMAL"
	FileVisibilityHidden FileVisibility = "HIDDEN"
	FileVisibilityLost   FileVisibility = "LOST"
)

var AllFileVisibility = []FileVisibility{
	FileVisibilityNormal,
	FileVisibilityHidden,
	FileVisibilityLost,
}

func (e FileVisibility) IsValid() bool {
	switch e {
	case FileVisibilityNormal, FileVisibilityHidden, FileVisibilityLost:
		return true
	}
	return false
}

func (e FileVisibility) String() string {
	return string(e)
}

func (e *FileVisibility) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FileVisibility(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FileVisibility", str)
	}
	return nil
}

func (e FileVisibility) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FileVisibility) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FileVisibility) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FilterOperator string

const (
	FilterOperatorAll FilterOperator = "ALL"
	FilterOperatorAny FilterOperator = "ANY"
)

var AllFilterOperator = []FilterOperator{
	FilterOperatorAll,
	FilterOperatorAny,
}

func (e FilterOperator) IsValid() bool {
	switch e {
	case FilterOperatorAll, FilterOperatorAny:
		return true
	}
	return false
}

func (e FilterOperator) String() string {
	return string(e)
}

func (e *FilterOperator) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FilterOperator(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FilterOperator", str)
	}
	return nil
}

func (e FilterOperator) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FilterOperator) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FilterOperator) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FsStatus string

const (
	FsStatusPending FsStatus = "PENDING"
	FsStatusSynced  FsStatus = "SYNCED"
	FsStatusFailed  FsStatus = "FAILED"
)

var AllFsStatus = []FsStatus{
	FsStatusPending,
	FsStatusSynced,
	FsStatusFailed,
}

func (e FsStatus) IsValid() bool {
	switch e {
	case FsStatusPending, FsStatusSynced, FsStatusFailed:
		return true
	}
	return false
}

func (e FsStatus) String() string {
	return string(e)
}

func (e *FsStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FsStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FsStatus", str)
	}
	return nil
}

func (e FsStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FsStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FsStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type HistoryColumn string

const (
	HistoryColumnName     HistoryColumn = "NAME"
	HistoryColumnLocation HistoryColumn = "LOCATION"
)

var AllHistoryColumn = []HistoryColumn{
	HistoryColumnName,
	HistoryColumnLocation,
}

func (e HistoryColumn) IsValid() bool {
	switch e {
	case HistoryColumnName, HistoryColumnLocation:
		return true
	}
	return false
}

func (e HistoryColumn) String() string {
	return string(e)
}

func (e *HistoryColumn) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HistoryColumn(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HistoryColumn", str)
	}
	return nil
}

func (e HistoryColumn) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *HistoryColumn) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e HistoryColumn) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortOrder string

const (
	SortOrderNameAsc      SortOrder = "NAME_ASC"
	SortOrderNameDesc     SortOrder = "NAME_DESC"
	SortOrderCreatedAsc   SortOrder = "CREATED_ASC"
	SortOrderCreatedDesc  SortOrder = "CREATED_DESC"
	SortOrderModifiedAsc  SortOrder = "MODIFIED_ASC"
	SortOrderModifiedDesc SortOrder = "MODIFIED_DESC"
	SortOrderSizeAsc      SortOrder = "SIZE_ASC"
	SortOrderSizeDesc     SortOrder = "SIZE_DESC"
)

var AllSortOrder = []SortOrder{
	SortOrderNameAsc,
	SortOrderNameDesc,
	SortOrderCreatedAsc,
	SortOrderCreatedDesc,
	SortOrderModifiedAsc,
	SortOrderModifiedDesc,
	SortOrderSizeAsc,
	SortOrderSizeDesc,
}

func (e SortOrder) IsValid() bool {
	switch e {
	case SortOrderNameAsc, SortOrderNameDesc, SortOrderCreatedAsc, SortOrderCreatedDesc, SortOrderModifiedAsc, SortOrderModifiedDesc, SortOrderSizeAsc, SortOrderSizeDesc:
		return true
	}
	return false
}

func (e SortOrder) String() string {
	return string(e)
}

func (e *SortOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrder", str)
	}
	return nil
}

func (e SortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TagDomain string

const (
	TagDomainDescriptive TagDomain = "DESCRIPTIVE"
	TagDomainAttribution TagDomain = "ATTRIBUTION"
	TagDomainQueue       TagDomain = "QUEUE"
	TagDomainUnlabeled   TagDomain = "UNLABELED"
	TagDomainCreation    TagDomain = "CREATION"
)

var AllTagDomain = []TagDomain{
	TagDomainDescriptive,
	TagDomainAttribution,
	TagDomainQueue,
	TagDomainUnlabeled,
	TagDomainCreation,
}

func (e TagDomain) IsValid() bool {
	switch e {
	case TagDomainDescriptive, TagDomainAttribution, TagDomainQueue, TagDomainUnlabeled, TagDomainCreation:
		return true
	}
	return false
}

func (e TagDomain) String() string {
	return string(e)
}

func (e *TagDomain) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TagDomain(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TagDomain", str)
	}
	return nil
}

func (e TagDomain) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TagDomain) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TagDomain) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TagEntryType string

const (
	TagEntryTypeNormal TagEntryType = "NORMAL"
	TagEntryTypeAlias  TagEntryType = "ALIAS"
)

var AllTagEntryType = []TagEntryType{
	TagEntryTypeNormal,
	TagEntryTypeAlias,
}

func (e TagEntryType) IsValid() bool {
	switch e {
	case TagEntryTypeNormal, TagEntryTypeAlias:
		return true
	}
	return false
}

func (e TagEntryType) String() string {
	return string(e)
}

func (e *TagEntryType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TagEntryType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TagEntryType", str)
	}
	return nil
}

func (e TagEntryType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TagEntryType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TagEntryType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TagFilterEffect string

const (
	TagFilterEffectInclusive TagFilterEffect = "INCLUSIVE"
	TagFilterEffectExclusive TagFilterEffect = "EXCLUSIVE"
)

var AllTagFilterEffect = []TagFilterEffect{
	TagFilterEffectInclusive,
	TagFilterEffectExclusive,
}

func (e TagFilterEffect) IsValid() bool {
	switch e {
	case TagFilterEffectInclusive, TagFilterEffectExclusive:
		return true
	}
	return false
}

func (e TagFilterEffect) String() string {
	return string(e)
}

func (e *TagFilterEffect) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TagFilterEffect(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TagFilterEffect", str)
	}
	return nil
}

func (e TagFilterEffect) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TagFilterEffect) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TagFilterEffect) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TagType string

const (
	TagTypeTag               TagType = "TAG"
	TagTypeArtist            TagType = "ARTIST"
	TagTypeCreator           TagType = "CREATOR"
	TagTypeContributor       TagType = "CONTRIBUTOR"
	TagTypeOwner             TagType = "OWNER"
	TagTypeQueue             TagType = "QUEUE"
	TagTypeRelated           TagType = "RELATED"
	TagTypeCreatedBefore     TagType = "CREATED_BEFORE"
	TagTypeCreatedOnOrBefore TagType = "CREATED_ON_OR_BEFORE"
	TagTypeCreatedOn         TagType = "CREATED_ON"
	TagTypeCreatedOnOrAfter  TagType = "CREATED_ON_OR_AFTER"
	TagTypeCreatedAfter      TagType = "CREATED_AFTER"
)

var AllTagType = []TagType{
	TagTypeTag,
	TagTypeArtist,
	TagTypeCreator,
	TagTypeContributor,
	TagTypeOwner,
	TagTypeQueue,
	TagTypeRelated,
	TagTypeCreatedBefore,
	TagTypeCreatedOnOrBefore,
	TagTypeCreatedOn,
	TagTypeCreatedOnOrAfter,
	TagTypeCreatedAfter,
}

func (e TagType) IsValid() bool {
	switch e {
	case TagTypeTag, TagTypeArtist, TagTypeCreator, TagTypeContributor, TagTypeOwner, TagTypeQueue, TagTypeRelated, TagTypeCreatedBefore, TagTypeCreatedOnOrBefore, TagTypeCreatedOn, TagTypeCreatedOnOrAfter, TagTypeCreatedAfter:
		return true
	}
	return false
}

func (e TagType) String() string {
	return string(e)
}

func (e *TagType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TagType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TagType", str)
	}
	return nil
}

func (e TagType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TagType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TagType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TraversalMode string

const (
	TraversalModeRecursive TraversalMode = "RECURSIVE"
	TraversalModeFlat      TraversalMode = "FLAT"
)

var AllTraversalMode = []TraversalMode{
	TraversalModeRecursive,
	TraversalModeFlat,
}

func (e TraversalMode) IsValid() bool {
	switch e {
	case TraversalModeRecursive, TraversalModeFlat:
		return true
	}
	return false
}

func (e TraversalMode) String() string {
	return string(e)
}

func (e *TraversalMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TraversalMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TraversalMode", str)
	}
	return nil
}

func (e TraversalMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TraversalMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TraversalMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type VisibilityFilter string

const (
	VisibilityFilterNormal VisibilityFilter = "NORMAL"
	VisibilityFilterHidden VisibilityFilter = "HIDDEN"
	VisibilityFilterLost   VisibilityFilter = "LOST"
	VisibilityFilterAny    VisibilityFilter = "ANY"
)

var AllVisibilityFilter = []VisibilityFilter{
	VisibilityFilterNormal,
	VisibilityFilterHidden,
	VisibilityFilterLost,
	VisibilityFilterAny,
}

func (e VisibilityFilter) IsValid() bool {
	switch e {
	case VisibilityFilterNormal, VisibilityFilterHidden, VisibilityFilterLost, VisibilityFilterAny:
		return true
	}
	return false
}

func (e VisibilityFilter) String() string {
	return string(e)
}

func (e *VisibilityFilter) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VisibilityFilter(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VisibilityFilter", str)
	}
	return nil
}

func (e VisibilityFilter) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VisibilityFilter) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VisibilityFilter) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
